version: '3.8'

services:
  web:
    build: .
    command: supervisord -c /app/supervisord.conf
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password@123
      - DB_NAME=axis_track
      - REDIS_HOST=redis
    volumes:
      - .:/app
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: axis_track
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
