# Generated by Django 4.0 on 2024-09-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechine_manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='axis',
            constraint=models.UniqueConstraint(fields=('axis_name', 'machine'), name='unique_axis_for_machine'),
        ),
    ]
