# Generated by Django 4.0 on 2024-09-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechine_manage_app', '0002_axis_unique_axis_for_machine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='axis',
            options={'permissions': [('can_edit_axis', 'Can edit axis'), ('can_create_axis', 'Can create axis'), ('can_delete_axis', 'Can delete axis')]},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'permissions': [('can_edit_machine', 'Can edit machine'), ('can_create_machine', 'Can create machine'), ('can_delete_machine', 'Can delete machine')]},
        ),
        migrations.AlterModelOptions(
            name='toolsinuse',
            options={'permissions': [('can_edit_toolsInUse', 'Can edit toolsInUse'), ('can_create_toolsInUse', 'Can create toolsInUse'), ('can_delete_toolsInUse', 'Can delete toolsInUse')]},
        ),
    ]
