# Generated by Django 4.0 on 2024-09-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechine_manage_app', '0003_alter_axis_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='axis',
            options={'permissions': [('can_edit_axis', 'Can Edit Axis'), ('can_create_axis', 'Can Create Axis'), ('can_delete_axis', 'Can Delete Axis')]},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'permissions': [('can_edit_machine', 'Can Edit Machine'), ('can_create_machine', 'Can Create Machine'), ('can_delete_machine', 'Can Delete Machine')]},
        ),
        migrations.AlterModelOptions(
            name='toolsinuse',
            options={'permissions': [('can_edit_toolsInUse', 'Can Edit ToolsInUse'), ('can_create_toolsInUse', 'Can Create ToolsInUse'), ('can_delete_toolsInUse', 'Can Delete ToolsInUse')]},
        ),
    ]
