# Generated by Django 4.0 on 2024-09-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechine_manage_app', '0004_alter_axis_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='axis',
            options={'permissions': [('can_modify_axis', 'Can modify axis'), ('can_create_axis', 'Can create axis'), ('can_destroy_axis', 'Can destroy axis')]},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'permissions': [('can_modify_machine', 'Can modify machine'), ('can_create_machine', 'Can create machine'), ('can_destroy_machine', 'Can destroy machine')]},
        ),
        migrations.AlterModelOptions(
            name='toolsinuse',
            options={'permissions': [('can_modify_toolsInUse', 'Can modify ToolsInUse'), ('can_create_toolsInUse', 'Can create ToolsInUse'), ('can_destroy_toolsInUse', 'Can destroy ToolsInUse')]},
        ),
    ]
