# Generated by Django 4.0 on 2024-09-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechine_manage_app', '0005_alter_axis_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolsinuse',
            options={'permissions': [('can_modify_toolsInUse', 'Can modify toolsInUse'), ('can_create_toolsInUse', 'Can create toolsInUse'), ('can_destroy_toolsInUse', 'Can destroy toolsInUse')]},
        ),
    ]
