# Generated by Django 4.0 on 2024-09-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechine_manage_app', '0006_alter_toolsinuse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='axis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={},
        ),
        migrations.AlterModelOptions(
            name='toolsinuse',
            options={},
        ),
    ]
